### ISSUE TITLE
Freezes when getting checkpoints or when training

### ISSUE THREAD

**Issue by ThatGuyCalledJesse** [pb4git/trackmania_rl_public#14]
As soon as the race starts, when either getting checkpoints from a manual run or when training, the game freezes. It never unfreezes.

**Comment by terafear** [comment]
Does it give you a error in the terminal?

**Comment by ThatGuyCalledJesse** [comment]
Not home now, but I can reproduce it, are you talking about the python console or the trackmania console?

**Comment by ThatGuyCalledJesse** [comment]
Ok I found what was wrong, the game gets automatically set to 0 speed

**Comment by ThatGuyCalledJesse** [comment]
To fix it run "set speed 1" in the TMInterface terminal
