### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by pavankay** [pb4git/trackmania_rl_public#23]
when I run train.py nothing happens

**Comment by terafear** [comment]
does it say anything in the terminal when you run it?

**Comment by pavankay** [comment]
I am running this with vs code. This is what is says in the terminal:

PS C:\Users\name\Downloads\trackmania_rl_public-main> & C:/Users/pavan/AppData/Local/Microsoft/WindowsApps/python3.11.exe c:/Users/name/Downloads/trackmania_rl_public-main/trackmania_rl_public-main/scripts/train.py
PS C:\Users\name\Downloads\trackmania_rl_public-main>

**Comment by terafear** [comment]
Have you gone thru the prerequisites and installation instructions? And added python to your path?

**Comment by pavankay** [comment]
after redoing everything installing the requirements and add python to path iam getting this error:

CREATE region=(-30320, -32226, -29680, -31746), output_idx=1
Traceback (most recent call last):
  File "C:\Users\name\Downloads\trackmania_rl_public-main\trackmania_rl_public-main\scripts\train.py", line 15, in <module>
    from trackmania_rl import buffer_management, misc, nn_utilities, tm_interface_manager
  File "C:\Users\name\Downloads\trackmania_rl_public-main\trackmania_rl_public-main\scripts\trackmania_rl\tm_interface_manager.py", line 72, in <module>
    create_dxcam()
  File "C:\Users\name\Downloads\trackmania_rl_public-main\trackmania_rl_public-main\scripts\trackmania_rl\tm_interface_manager.py", line 59, in create_dxcam
    camera = dxcam.create(output_idx=output_idx, output_color="BGRA", region=region, max_buffer_len=1)
  File "C:\Users\name\AppData\Local\Programs\Python\Python310\lib\site-packages\dxcam\__init__.py", line 112, in create
    return __factory.create(
  File "C:\Users\name\AppData\Local\Programs\Python\Python310\lib\site-packages\dxcam\__init__.py", line 71, in create
    camera = DXCamera(
  File "C:\Users\name\AppData\Local\Programs\Python\Python310\lib\site-packages\dxcam\dxcam.py", line 46, in __init__
    self._validate_region(self.region)
  File "C:\Users\name\AppData\Local\Programs\Python\Python310\lib\site-packages\dxcam\dxcam.py", line 233, in _validate_region
    raise ValueError(
ValueError: Invalid Region: Region should be in 1920x1080
Exception ignored in: <function DXCamera.__del__ at 0x00000285AA94C820>
Traceback (most recent call last):
  File "C:\Users\name\AppData\Local\Programs\Python\Python310\lib\site-packages\dxcam\dxcam.py", line 243, in __del__
    self.release()
  File "C:\Users\name\AppData\Local\Programs\Python\Python310\lib\site-packages\dxcam\dxcam.py", line 238, in release
    self.stop()
  File "C:\Users\name\AppData\Local\Programs\Python\Python310\lib\site-packages\dxcam\dxcam.py", line 138, in stop
    if self.is_capturing:
AttributeError: 'DXCamera' object has no attribute 'is_capturing'
PS C:\Users\name\Downloads\trackmania_rl_public-main\trackmania_rl_public-main\scripts>

**Comment by terafear** [comment]
i am not very familiar with Dxcam have you joined the discord thread and see if someone else may be able to help?

**Comment by pavankay** [comment]
this was not happening before but i think that was because I was using python 3.11

**Comment by terafear** [comment]
Have you tried reinstalling python 3.10?

**Comment by pavankay** [comment]
I tried and got the same error

**Comment by terafear** [comment]
Hmm I'm not so sure then. I'd say ask in the discord and maybe search the dxcam repository to see if a similar issue has happened to someone else.

**Comment by Agade09** [comment]
This is your problem:
ValueError: Invalid Region: Region should be in 1920x1080

dxcam is given an invalid region. Make sure the TMI window is somewhere visible on a screen, if the error persists, I have no other idea than to print out the region and trying to debug it

**Comment by pavankay** [comment]
i dont see an option to change my screen resolution

**Comment by pb4git** [comment]
This option does not exist in this codebase.
Agade and I use similar hardware: and have not felt the need to include flexibility there.

**Comment by pavankay** [comment]
also I dont understand this error:  File "c:\Users\name\Downloads\trackmania_rl_public-main\trackmania_rl_public-main\scripts\trackmania_rl\agents\iqn.py", line 67, in __init__
    self.float_inputs_mean = torch.tensor(float_inputs_mean, dtype=torch.float32).to("cuda")
  File "C:\Users\name\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\cuda\__init__.py", line 289, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

**Comment by pavankay** [comment]
> This option does not exist in this codebase. Agade and I use similar hardware: and have not felt the need to include flexibility there.

I meant the Trackmainia interface

**Comment by pavankay** [comment]
Iam using cuda 12.1

**Comment by terafear** [comment]
Ensure you follow the 'Prerequisites' section in the README to download the correct versions of Python, PyTorch, etc., which helps us ascertain that any errors encountered aren't due to version issues. Regarding the resolution, please set it in game as specified in the README, window the game, and make sure it's visibly active on your monitor, without any overlaying applications and not minimized.

**Comment by pavankay** [comment]
I dont know how to change my resoulution. Also should i use pytorch for 12.1 or use 11.8 and downgrade my cuda

**Comment by pavankay** [comment]
I recloned this project and now starts on tmi interface but i get this error: CREATE region=(640, 300, 1280, 780), output_idx=0
RecursiveScriptModule(
  original_name=Agent
  (img_head): RecursiveScriptModule(
    original_name=Sequential
    (0): RecursiveScriptModule(original_name=Conv2d)
    (1): RecursiveScriptModule(original_name=LeakyReLU)
    (2): RecursiveScriptModule(original_name=Conv2d)
    (3): RecursiveScriptModule(original_name=LeakyReLU)
    (4): RecursiveScriptModule(original_name=Conv2d)
    (5): RecursiveScriptModule(original_name=LeakyReLU)
    (6): RecursiveScriptModule(original_name=Conv2d)
    (7): RecursiveScriptModule(original_name=LeakyReLU)
    (8): RecursiveScriptModule(original_name=Flatten)
  )
  (float_feature_extractor): RecursiveScriptModule(
    original_name=Sequential
    (0): RecursiveScriptModule(original_name=Linear)
    (1): RecursiveScriptModule(original_name=LeakyReLU)
    (2): RecursiveScriptModule(original_name=Linear)
    (3): RecursiveScriptModule(original_name=LeakyReLU)
  )
  (A_head): RecursiveScriptModule(
    original_name=Sequential
    (0): RecursiveScriptModule(original_name=Linear)
    (1): RecursiveScriptModule(original_name=LeakyReLU)
    (2): RecursiveScriptModule(original_name=Linear)
  )
  (V_head): RecursiveScriptModule(
    original_name=Sequential
    (0): RecursiveScriptModule(original_name=Linear)
    (1): RecursiveScriptModule(original_name=LeakyReLU)
    (2): RecursiveScriptModule(original_name=Linear)
  )
  (iqn_fc): RecursiveScriptModule(original_name=Linear)
  (lrelu): RecursiveScriptModule(original_name=LeakyReLU)
)
 Could not load weights
 Could not load stats
Disabled FPS cap of process 20108

**Comment by Agade09** [comment]
This is not an error.

Could not load weights
Could not load stats

Only means that you're starting a new run. So it doesn't have saved weights and run statistics (racing time, training loss...)  to load.

**Comment by pavankay** [comment]
Ok but in trackmainia the timer is frozen and the screen

**Comment by pavankay** [comment]
now iam getting the dxcam error this is wierd

**Comment by pavankay** [comment]
could not solve the problem
