### ISSUE TITLE
Train.py wont load trackmania_rl

### ISSUE THREAD

**Issue by BERHAULTAurelien** [pb4git/trackmania_rl_public#24]
When i launch the script train.py by python.exe \scripts\train.py , An error appear, No module named 'trackmania_rl'

**Comment by ThatGuyCalledJesse** [comment]
Before running train.py, did you first run
`pip install -r requirements.txt` and `pip install -e .`? Because those 2 commands are needed to run

**Comment by BERHAULTAurelien** [comment]
Yes i did all but still the same probleme

**Comment by BERHAULTAurelien** [comment]
So i changed of computer and it works perfectly so idk what was the issue
