### ISSUE TITLE
IndexError: index -1 is out of bounds for axis 0 with size 0

### ISSUE THREAD

**Issue by terafear** [pb4git/trackmania_rl_public#7]
HI, anytime i run "python ./scripts/observe_manual_run_to_extract_checkpoints.py" and play thru the map it stutters real bad at the ending (i assume thats normal) but when i go back to the terminal i see this. when looking inside the maps folder there is a map.npy file.

C:\Users\andre\Desktop\trackmania_rl_public-main\scripts\observe_manual_run_to_extract_checkpoints.py:75: RuntimeWarning: invalid value encountered in floor_divide
  index_first_pos_in_new_zone = np.unique(c // zone_length, return_index=True)[1][1:]
Exception in thread Thread-1 (_main_thread):
Traceback (most recent call last):
  File "C:\Users\andre\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Users\andre\AppData\Local\Programs\Python\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\andre\AppData\Local\Programs\Python\Python310\lib\site-packages\tminterface\interface.py", line 843, in _main_thread
    self._process_server_message()
  File "C:\Users\andre\AppData\Local\Programs\Python\Python310\lib\site-packages\tminterface\interface.py", line 881, in _process_server_message
    self.client.on_checkpoint_count_changed(self, current, target)
  File "C:\Users\andre\Desktop\trackmania_rl_public-main\scripts\observe_manual_run_to_extract_checkpoints.py", line 59, in on_checkpoint_count_changed
    self.extract_cp_distance_interval()
  File "C:\Users\andre\Desktop\trackmania_rl_public-main\scripts\observe_manual_run_to_extract_checkpoints.py", line 86, in extract_cp_distance_interval
    (2 * client.raw_position_list[-1] - self.zone_centers[-1])[None, :],
IndexError: index -1 is out of bounds for axis 0 with size 0

**Comment by ausstein** [comment]
you need to run as an admin, otherwise it can't acess the memory of the thread

**Comment by pb4git** [comment]
I have absolutely no idea what causes this error.
No, it is not normal that the game stutters at the end.

**Comment by NumseBacon** [comment]
Did you install TMI correctly?

**Comment by terafear** [comment]
Yes I belive I have. I used the version in the Readme. And can launch the game thru TMI and see the console when I launch it

**Comment by terafear** [comment]
upon remmoving everything and reinstalling python and the repository i am still getting the same error. but i did notice this time in the TMI terminal i get the error "client failed to respond for message type S_ON_CHECKPOINT_COUNT_CHANGED in the timeout window: 2000ms" as well as the same error in python

**Comment by pb4git** [comment]
Given what you describe, I'd suggest trying one of TMInterface's example scripts, to see if it connects.

https://github.com/donadigo/TMInterfaceClientPython/blob/master/examples/print_values.py

**Comment by terafear** [comment]
Gave print_values.py a try and it is working as intended properly printing Time,Speed,Position,Velocity and YPW
as well as not throwing any errors in tminterfaces terminal

**Comment by terafear** [comment]
Gonna try a different pc with similar specs this weekend. Will try on win 11 and 10. As well as wipe the drive and reinstall windows on the one currently having issues to see if that fixes anything.

**Comment by terafear** [comment]
Initially, I was encountering an index error while running 'observe_manual_run_to_extract_checkpoints.py.' However, this issue mysteriously resolved itself without any changes to the code or my system. It's important to note that I was getting the index error even when I was not doing the steps i found that could replicate the index error.

I discovered a way to reliably replicate the index error tho by following these steps:

Run 'observe_manual_run_to_extract_checkpoints.py.'
Play through the map.
Play through the map again without restarting the script.

Since the error resolved itself i have not had the index error anytime execpt when doing the steps listed above.
